import Head from 'next/head'
import MiddleBar from '../components/MiddleBar'


export default function Home() {
  return (
    <>
    <Head>
      <title>Shri Shivaji College</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <MiddleBar/>
    </>
  )
}
